### ISSUE TITLE
wrongly throwing cyclical error due to typo

### ISSUE THREAD

**Issue by tomertwist** [yazgazan/jaydiff#13]
The bug comes from diff.go, line 193:

if canAddr(rhs) && !isEmptyMapOrSlice(**lhs**) {

should be 

if canAddr(rhs) && !isEmptyMapOrSlice(**rhs**) {

**Comment by yazgazan** [comment]
Hi @tomertwist 

Thanks for catching this bug and pinpointing the issue in the code 🙂 .

Can you provide a code example triggering this error so I can add it to the tests ?

**Comment by yazgazan** [comment]
There is a remaining limitation in the circular reference detection that you might still hit: addressable values (excluding empty maps and slices) can trigger a false positive when repeated in a non-circular way.

I just opened an issue on this and will try to tackle it this week-end. See #15 for more details.

**Comment by tomertwist** [comment]
Perfect, thanks!
